hw6 types
MaryZaiko/my-app-React pull request #4
Opened 2022-05-11 09:53 UTC by MaryZaiko

2022-05-12 20:15 UTC, vl-domorad requested changes
В целом все ок, посмотри мои комменты, но не мерж до занятия, разберем на занятии все вопросы подробнее

2022-05-12 20:15 UTC, vl-domorad commented on src/common/types hw.ts
> +  let UsersWithEducation = users.filter((user) => user.hasEducation);
переменные с маленькой буквы!!!

2022-05-12 20:15 UTC, vl-domorad commented on src/common/types.ts
> +type SortCountries = (item: Array<Country>) => void;
у тебя же тут страны возвращаются, соответственно точно не void

2022-05-12 20:15 UTC, vl-domorad commented on src/common/types.ts
> +  let allCurrencyName: string[] = []; // почему так?
Потому что когда ты определяешь массив в переменную let, ts хочет знать что именно после ты в него поместишь и ты строго определяешь, что в него потом ляжет

2022-05-12 20:15 UTC, vl-domorad commented on src/common/types.ts
> +    allCurrencyName.push(i.currency_name);
можно просто return arr.map

2022-05-12 20:15 UTC, vl-domorad commented on src/common/types.ts
> +    allCurrencyName.push(i.currency_name);
не создавая при этом новый массив

2022-05-12 20:15 UTC, vl-domorad commented on src/common/types.ts
> +  countries.sort((a, b) => (a.city > b.city ? 1 : -1));
мутируешь исходные данные, мутировать нельзя, подумать как сделать, чтобы создавался новый массив и при этом не через forEach

2022-05-12 20:15 UTC, vl-domorad commented on src/components/Input/Input.tsx
> +  onChange?: (e: ChangeEventHandler<HTMLInputElement> | undefined) => void;
Так почему тебе не сделать обработку внутри самого Input, чтобы у тебя сразу точно отдавало value: string? вместо того, чтобы во всех родительских постоянно типизировать event

2022-05-12 20:15 UTC, vl-domorad commented on src/components/Sidebar/Sidebar.tsx
>  export default (props:any) => {
Тебе тут пропсы вообще не нужны, поэтому их можно просто убрать

2022-05-13 08:05 UTC, MaryZaiko commented on src/common/types.ts
> +    allCurrencyName.push(i.currency_name);
если с делать arr.map, тогда измениться исходный массив. а нам надо получить просто массив из одних только валют.

2022-05-13 08:12 UTC, MaryZaiko commented on src/components/Sidebar/Sidebar.tsx
>  export default (props:any) => {
если их убрать, то появляется ошибка.

2022-05-17 14:20 UTC, vl-domorad requested changes
В целом все хорошо, исправляй, но не мержить! на занятии объясню почему

2022-05-17 14:20 UTC, vl-domorad commented on src/components/HeaderPages/HeaderPages.tsx
> +          { ["darkHeader"]: !isLightTheme }
Это можно в один объект через запятую засунуть

2022-06-03 11:19 UTC, vl-domorad approved these changes
Умничка
С кодом все в порядке, единственное что нужно этот МР смержить и дальше на него навешивать, потому что с каждым новым коммитом мне нужно проверять все предыдущее, но работу я принимаю.
По поводу вопросов закомментированных на занятии подойди, разберемся как лучше оптимизировать

2022-06-03 12:07 UTC, merged